homeworks/alexandr.gonor_alexgonor/service_desk/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'tickets#index'

  scope "(:locale)", locale: /en/ do
    resources :tickets do
      resources :comments
    end
  end

  scope path: 'ticket/:id', controller: :tickets do
    put '/:status_of_ticket', to: 'tickets#resolved', status_of_ticket: /resolved/, as: :resolved
    put '/:status_of_ticket', to: 'tickets#take_in_work', status_of_ticket: /take_in_work/, as: :take_in_work
    put '/:status_of_ticket', to: 'tickets#closed', status_of_ticket: /closed/, as: :closed
  end

  get '/:locale' => 'tickets#index'

  mount ActionCable.server => '/cable'

end

homeworks/alexandr.gonor_alexgonor/service_desk/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  # after_create_commit { BroadcastMessageJob.perform_later self }
end

homeworks/alexandr.gonor_alexgonor/service_desk/app/models/ticket.rb
# Ticket model
class Ticket < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy

  enum type_of_ticket: %i[repaire service_request permisiion_request]
  enum status_of_ticket: %i[newly_created in_progress closed resolved]
  enum responsible_unit: %i[repair service security]

  validates :title, length: { minimum: 10, maximum: 100 }, presence: true, uniqueness: true
  validates :detailed_description, length: { minimum: 20, maximum: 200 }
  validates :deadline, :type_of_ticket, :responsible_unit, presence: true

  mount_uploader :attachment, AttachmentUploader

  filterrific(
    available_filters: %i[
      with_type_of_ticket
      with_status_of_ticket
      with_responsible_unit
    ]
  )
  scope :with_type_of_ticket, lambda { |type_of_tickets|
    return nil if type_of_tickets == ['']
    where(type_of_ticket: [*type_of_tickets])
  }

  scope :with_status_of_ticket, lambda { |status_of_tickets|
    return nil if status_of_tickets == ['']
    where(status_of_ticket: [*status_of_tickets])
  }

  scope :with_responsible_unit, lambda { |responsible_units|
    return nil if responsible_units == ['']
    where(responsible_unit: [*responsible_units])
  }

end

homeworks/alexandr.gonor_alexgonor/service_desk/app/models/user.rb
# User devise model
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :tickets
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum type_of_user: %i[user executor]

  # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  private

  def avatar_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end

  validates :position_in_the_company, presence: true
  validates :username, presence: true
  validates :type_of_user, presence: true
end

homeworks/alexandr.gonor_alexgonor/service_desk/app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!
  def show
    @messages = Message.all
  end
end

homeworks/alexandr.gonor_alexgonor/service_desk/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_ticket, only: %i[show edit update destroy take_in_work resolved closed]
  before_action :owned_ticket, only: %i[edit update destroy]
  before_action :ticket, only: :new

  def index
    (@filterrific = initialize_filterrific(
      Ticket,
      params[:filterrific],
      select_options: {
        with_type_of_ticket: %w[repaire service_request permisiion_request],
        with_status_of_ticket: %w[newly_created in_progress closed resolved],
        with_responsible_unit: %w[repair service security]
      },
      default_filter_params: {},
      available_filters: %i[with_type_of_ticket with_status_of_ticket with_responsible_unit]
    )) || return

    @tickets = @filterrific.find.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  rescue ActiveRecord::RecordNotFound => e
    logger.debug("Had to reset filterrific params: #{e.message}")
    redirect_to(reset_filterrific_url(format: :html)) && return
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new; end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    @ticket.status_of_ticket = :newly_created

    if @ticket.save
      UserMailer.ticket_email(@current_user).deliver
      flash[:success] = 'Ticket created'
      redirect_to tickets_path
    else
      flash[:warning] = 'Ticket not created'
      render :new
    end
  end

  def edit; end

  def update
    if @ticket.update(ticket_params)
      flash[:success] = 'Ticket updated'
      redirect_to tickets_path
    else
      flash[:warning] = 'Ticket not updated'
      render 'edit'
    end
  end

  def destroy
    if @ticket.destroy
      flash[:success] = 'Ticket deleted'
      redirect_to tickets_path
    else
      flash[:warning] = "Ticket doesn't exist"
    end
  end

  def take_in_work
    if current_user.executor? && @ticket.newly_created?
      @ticket.update(executor: current_user.email, status_of_ticket: 'in_progress')
      find_user_and_send_email

      redirect_to ticket_path
    else
      flash[:warning] = 'Action is not avalible'

      redirect_to root_path
    end
  end

  def resolved
    if current_user.email == @ticket.executor && @ticket.in_progress?
      @ticket.update(status_of_ticket: 'resolved')
      find_user_and_send_email

      redirect_to ticket_path
    else
      flash[:warning] = 'Action is not avalible'

      redirect_to root_path
    end
  end

  def closed
    if current_user.id == @ticket.user_id && @ticket.in_progress?
      @ticket.update(status_of_ticket: 'closed')
      find_executor_and_send_email

      redirect_to ticket_path
    else
      flash[:warning] = 'Action is not avalible'

      redirect_to root_path
    end
  end

  private

  def find_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:title, :detailed_description, :type_of_ticket, :executor, :deadline,
                                   :history, :status_of_ticket, :responsible_unit, :attachment)
  end

  def ticket
    @ticket ||= Ticket.new
  end

  def owned_ticket
    if current_user.id != @ticket.user_id
      flash[:alert] = "That ticket doesn't belong to you!"
      redirect_to root_path
    end
  end

  def find_user_and_send_email
    @user = User.find_by(id: @ticket.user_id)
    UserMailer.take_in_work_email(@user, @ticket).deliver
  end

  def find_executor_and_send_email
    @executor = User.find_by(email: @ticket.executor)
    UserMailer.closed_email(@executor, @ticket).deliver
  end
end

homeworks/alexandr.gonor_alexgonor/service_desk/app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

homeworks/alexandr.gonor_alexgonor/service_desk/app/views/chat_rooms/show.html.erb
<% content_for :title, 'admin | Action Cable Chat' %>
<div class="header">
  <div class="team-menu">ActionCable</div>

  <div class="channel-menu">
    <span class="channel-menu_name"><span class="channel-menu_prefix">#</span> admin</span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <ul class="channel_list">
        <li class="channel active">
          <a class="channel_name"><span><span class="prefix">#</span>admin</span></a>
        </li>
        <li class="channel">
          <a class="channel_name"><span class="unread">10</span><span><span class="prefix">#</span>general</span></a>
        </li>
      </ul>
    </div>
    <div class="listings_direct-messages">
      <h2 class="listings_header">Direct Messages</h2>
      <ul class="channel_list">
        <li class="channel">
          <a class="channel_name"><span class="unread">20</span><span><span class="prefix"> </span>dhh@basecamp.com</span></a>
        </li>
      </ul>
    </div>
  </div>
  <div class="message-history" id="messages">
    <%= render @messages %>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic"></span><span class="user-menu_username"><%= current_user.email %></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
  </div>
  <div class="input-box">
    <input type="text" class="input-box_text" id="message_input"/>
  </div>
</div>

homeworks/alexandr.gonor_alexgonor/service_desk/app/views/messages/_message.html.erb
<div class="message">
  <a href="" class="message_profile-pic"></a>
  <a href="" class="message_username"><%= message.user.username %></a>
  <span class="message_timestamp">
    <%= message.created_at %>
  </span>
  <span class="message_star"></span>
  <span class="message_body">
    <%= message.body %>
  </span>
</div>

homeworks/alexandr.gonor_alexgonor/service_desk/app/views/tickets/_list.html.haml
#filterrific_results
  %div
    = page_entries_info @tickets
  .panel.panel-default
    %h1.panel-heading= t('tickets._list.list_of_tickets')
    = button_to "New", new_ticket_path, method: :get
    .panel-body
      %table.table.table-striped.table-bordered.table-hover.table-condensed
        %tr
        %th= t('tickets._list.status_of_ticket')
        %th= t('tickets._list.type_of_ticket')
        %th= t('tickets._list.title')
        %th= t('tickets._list.detailed_description')
        %th= t('tickets._list.responsible_unit')
        %th= t('tickets._list.author')
        %th= t('tickets._list.executor')
        %th= t('tickets._list.deadline')
        %th= t('tickets._list.history')
        %th= t('tickets._list.attachment')
        %th= t('tickets._list.created_at')
        %th= t('tickets._list.updated_at')
        %th= t('tickets._list.available_actions')
        - @tickets.each do |ticket|
          %tr
            %td= ticket.status_of_ticket
            %td= ticket.type_of_ticket
            %td= ticket.title
            %td= ticket.detailed_description
            %td= ticket.responsible_unit
            %td
              = ticket.user.username
              = ticket.user.email
            %td= ticket.executor
            %td= ticket.deadline
            %td= ticket.history
            %td
              - if ticket.attachment?
                = image_tag(ticket.attachment_url(:thumb))
                %br
                = link_to 'Download file', ticket.attachment.url
            %td= ticket.created_at
            %td= ticket.updated_at
            %td
              = button_to "Show ticket", ticket_path(@user, ticket), method: :get
              %br
              - if ticket_of_current_user?(ticket)
                = button_to "Edit ticket", edit_ticket_path(@user, ticket), method: :get
                %br
                = button_to "Delete ticket", ticket_path(@user, ticket), method: :delete, data: { confirm: 'Are you sure?' }
= will_paginate tickets

homeworks/alexandr.gonor_alexgonor/service_desk/app/views/tickets/index.html.haml
.panel.panel-default
  %h3.panel-heading= t('tickets.index.filter_of_tickets')
  = form_for_filterrific @filterrific do |f|
    %div
      = t('tickets.index.filter_type')
      \#{f.select( :with_type_of_ticket, @filterrific.select_options[:with_type_of_ticket], { include_blank: '- Any -', multiple: true } )}

      = t('tickets.index.filter_status')
      \#{f.select( :with_status_of_ticket, @filterrific.select_options[:with_status_of_ticket], { include_blank: '- Any -', multiple: true } )}

      = t('tickets.index.filter_responsible_unit')
      \#{f.select( :with_responsible_unit, @filterrific.select_options[:with_responsible_unit], { include_blank: '- Any -', multiple: true } )}

    %div
      = link_to(                 |
          'Reset filters',       |
          reset_filterrific_url, |
        )
    = render_filterrific_spinner
  = render(                         |
      partial: 'tickets/list',      |
      locals: { tickets: @tickets } |
    )                               |

homeworks/alexandr.gonor_alexgonor/service_desk/app/views/tickets/show.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          .lead Ticket params
        .panel-body
          .form-group
            %p
            %strong Title:
            = @ticket.title
          .form-group
            %p
              %strong Status of ticket:
              = @ticket.status_of_ticket
          .form-group
            %p
              %strong Type of ticket:
              = @ticket.type_of_ticket.humanize
          .form-group
            %p
              %strong Detailed description:
              = @ticket.detailed_description
          .form-group
            %p
              %strong Responsible unit:
              = @ticket.responsible_unit.humanize
          .form-group
            %p
              %strong Author:
              = @ticket.user.email
          .form-group
            %p
              %strong Executor:
              = @ticket.executor
          .form-group
            %p
              %strong Deadline:
              = @ticket.deadline
          .form-group
            %h4 Comments
            .comments{:id => "comments_#{@ticket.id}"}
              - if @ticket.comments
                = render @ticket.comments, ticket: @ticket
          .form-group
            %h4 Add a comment:
            = render 'comments/form'
          .form-group
            - if current_user.email == @ticket.executor && @ticket.in_progress?
              = button_to 'Resolved', resolved_path(@ticket, status_of_ticket: 'resolved'), method: :put
            -elsif current_user.executor? && @ticket.newly_created?
              = button_to 'Take in work', take_in_work_path(@ticket, status_of_ticket: 'take_in_work'), method: :put
            -elsif current_user.id == @ticket.user_id && @ticket.in_progress?
              = button_to 'Close', closed_path(@ticket, status_of_ticket: 'closed'), method: :put
          .form-group
            = link_to 'Back', tickets_path