homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Attachinary::Engine => "/attachinary"
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'landing#index'
  get 'pages/privacy_policy'

  resources :articles, only: [:index, :show]
  resources :events_reviews, only: [:index, :show]
  resources :announcements, only: [:index, :show]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/models/announcement.rb
class Announcement < ApplicationRecord
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/models/article.rb
class Article < ApplicationRecord
  mount_uploaders :attachments, AttachmentUploader
  has_attachments :images, maximum: 6, accept: [:jpg, :png, :gif]
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/models/user.rb
  class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.create_from_omniauth(params)
    user = find_or_create_by(email: params.info.email, uid: params.uid)
    user.update({
      token: params.credentials.token,
      name: params.info.name,
      avatar: params.info.image
    })
    user
  end
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  require 'koala'

  def index
    # @graph = Koala::Facebook::API.new('EAACGmrcnWT4BAGb4aKVNs0kHFZB3ZB2ijB0PIQoTjOPidZC96QqdX3zDEDe3rnowoG9ZAq6NQ7JN8qbcNu2eXziU41jW5tJhbwB8wMYoQugstoKzBXYAhkuWrA3sLEhLSL6oLQSallFCgWErysYCGOTta9ISqlxqS2OqJX4U3azPwaaZBjjpF5RQgkxLZCSk2pvE8ffNReygZDZD')
    # @user = @graph.get_object("me")
    # user = Authentication.where(user_id: current_user.id, provider: "facebook").first
    # oauth_access_token = user.token
    # @graph = Koala::Facebook::API.new(oauth_access_token)
    # @posts = @graph.get_connection('me', 'posts',{ fields: ['id', 'message', 'link', 'name', 'description', "likes.summary(true)", "shares", "comments.summary(true)"]})

    @announcements = Announcement.where('show_on_site = ?', true).order('created_at DESC')

  end

  def show
    @announcement = Announcement.find(params[:id])

  end
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where('show_on_site = ? AND event_review = ?', true, false).order('created_at DESC')
    Article.includes(:image_files).all
  end

  def show
    @article = Article.find(params[:id])
    Article.includes(:image_files).all
  end

end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/controllers/events_reviews_controller.rb
class EventsReviewsController < ApplicationController
  def index
    @events_reviews = @articles = Article.where('show_on_site = ? AND event_review = ?', true, true).order('created_at DESC')
  end
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.where('show_on_site = ? AND show_on_main_page = ? AND event_review = ?',
     true, true, false).order('updated_at DESC')
    @events_reviews = Article.where('show_on_site = ? AND show_on_main_page = ? AND event_review = ?',
     true, true, true).order('updated_at DESC')
  end
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def privacy_policy
  end
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/helpers/application_helper.rb
module ApplicationHelper
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/helpers/articles_helper.rb
module ArticlesHelper
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/helpers/landing_helper.rb
module LandingHelper
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/helpers/pages_helper.rb
module PagesHelper
end

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/views/announcements/index.html.erb
<h1 class="text-center">Announces list</h1>
<div class="row">
  <% @announcements.each do |announce| %>

    <%= link_to(announce) do %>
      <div class="center-block">
        <%=raw announce.link %>
      </div>

    <% end %>
  <% end %>
</div>

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/views/events_reviews/index.html.erb
<h1 class="text-center">Events reviews list</h1>
<div>
  <% @events_reviews.each do |event_review| %>
    <%= link_to(event_review) do %>
      <%= event_review.title %><br>
      <%= event_review.short_description %><br>
      <% if event_review.images? %>
        <% event_review.images.each do |image| %>
           <%= cl_image_tag(image.path, { size: '125x125', crop: :fit }) %>
        <% end %>
      <% else %>
        <img src="http://placehold.it/125x94" alt="...">
      <% end %>
      <hr>
    <% end %>
  <% end %>
</div>

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/views/landing/index.html.erb
<br>
<h1 class="text-center">Top events reviews</h1>
<div>
  <% @events_reviews.each do |event_review| %>
    <%= link_to(event_review) do %>
      <%= event_review.title %><br>
      <%= event_review.short_description %><br>
      <% if event_review.images? %>
        <% event_review.images.each do |image| %>
           <%= cl_image_tag(image.path, { size: '125x125', crop: :fit }) %>
        <% end %>
      <% else %>
        <img src="http://placehold.it/125x94" alt="...">
      <% end %>
      <hr>
    <% end %>
  <% end %>
</div>
<div class="float-right">
  <%= link_to 'See all events reviews', events_reviews_path %>
</div>


<br>
<h1 class="text-center">Top articles</h1>
<div>
  <% @articles.each do |article| %>
    <%= link_to(article) do %>
      <%= article.title %><br>
      <%= article.short_description %><br>
      <% if article.images? %>
        <% article.images.each do |image| %>
         <%= cl_image_tag(image.path, { size: '125x125', crop: :fit }) %>
        <% end %>
      <% else %>
        <img src="http://placehold.it/125x94" alt="...">
      <% end %>
      <hr>
  <% end %>
<% end %>
</div>
<div class="float-right">
  <%= link_to 'See all articles', articles_path %>
</div>

homeworks/ihor.trypolskyi_ihortrypolskyi/development with docker/hata/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HR-хата</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='container'>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>